/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import com.cepardov.Utilidades.FuncionesSQL;
import com.cepardov.Utilidades.FuncionesSystem;
import com.cepardov.Utilidades.jcTrayIcon;
import java.awt.TrayIcon;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author cepardov
 */
public class Escritorio extends javax.swing.JFrame {
     jcTrayIcon jct = new jcTrayIcon( this );
     FuncionesSystem fs=new FuncionesSystem();
     FuncionesSQL data=new FuncionesSQL();
     String usuario=null;
     Object[][] dtPrev;
     Timer timer;
     String fechaHoraAnterior;
     String fechaHoraActual;
     
   /**
     * Creates new form Escritorio
     */
    public Escritorio(){
        initComponents();
        setState(JFrame.MAXIMIZED_BOTH);
        timer = new Timer(); 
        timer.schedule (new RemindTask(),0, 60000);
        fechaHoraAnterior=fs.fechahora();
        this.lbltiempo.setText(fs.fechahora());
        this.lblultimacita.setText("");
        this.lblultimaobs.setText("");
        this.lblobservacion.setText("");
        this.lblcita.setText("");
    }
    
    public Escritorio(String nombre, String Apellido, String Usuario){
        initComponents();
        usuario = Usuario;
        jct.MensajeTrayIcon("Bienvenido (a) "+nombre+" "+Apellido, TrayIcon.MessageType.INFO);
        jct.MensajeTrayIcon("Cargando componentes de la aplicación...", TrayIcon.MessageType.INFO);
        jct.MensajeTrayIcon("Conectando con base de datos y comprobando la integridad de esta", TrayIcon.MessageType.INFO);
        setState(JFrame.MAXIMIZED_BOTH);
        timer = new Timer(); 
        timer.schedule (new RemindTask(),0, 60000);
        fechaHoraAnterior=fs.fechahora();
        this.lbltiempo.setText(fs.fechahora());
        this.lblultimacita.setText("");
        this.lblultimaobs.setText("");
        this.lblobservacion.setText("");
        this.lblcita.setText("");
    }
    
    public void BuscaCita() throws ClassNotFoundException, SQLException{
        //Consulta y setea hora actual del sistema en variable local fechaHora desde clase funciones de sistema
        fechaHoraAnterior=fechaHoraActual;
        this.lbltiempo.setText(fechaHoraAnterior);
        fechaHoraActual=fs.fechahora();
        
        System.out.println("anterior="+fechaHoraAnterior);
        System.out.println("actual="+fechaHoraActual);
        
        this.lblultimacita.setText(this.lblcita.getText());
        this.lblultimaobs.setText(this.lblobservacion.getText());
        //Busca nuevas citas
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/BDSis", "root", "");
        Statement st = conexion.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM  `Cita` WHERE `fecha` BETWEEN  '"+fechaHoraAnterior+"' AND '"+fechaHoraActual+"'");
        while (rs.next()) {
            this.lblcita.setText("Usted Tiene una cita con"+" "+rs.getObject("nombre").toString()+"\n "+rs.getObject("fecha").toString());
            this.lblobservacion.setText("Observación: "+rs.getObject("observacion"));
            jct.MensajeTrayIcon(lblcita.getText(), TrayIcon.MessageType.INFO);
            System.out.println("result "+rs.getObject("idCita"));
            if(rs.getObject("idCita").toString().isEmpty()){
                jct.MensajeTrayIcon("No na", TrayIcon.MessageType.INFO);
            }
            }   
        rs.close();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lbltiempo = new javax.swing.JLabel();
        lblcita = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblobservacion = new javax.swing.JLabel();
        lblultimacita = new javax.swing.JLabel();
        lblultimaobs = new javax.swing.JLabel();
        btnhistarial = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuCliente = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        btnBuscaCliente = new javax.swing.JMenuItem();
        selCambiaClave = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        p.setAutoscrolls(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Notificaciones Pendientes"));

        lbltiempo.setText("Hora");

        lblcita.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblcita.setText("No se encontraron nuevas notificaciones...");
        lblcita.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setText("Última Actualización: ");

        lblobservacion.setForeground(new java.awt.Color(255, 39, 0));
        lblobservacion.setText("Observacion");

        lblultimacita.setText("jLabel2");

        lblultimaobs.setText("jLabel3");

        btnhistarial.setText("Ver Historial");
        btnhistarial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhistarialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblobservacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblultimacita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblultimaobs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnhistarial)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltiempo)
                    .addComponent(jLabel1))
                .addGap(5, 5, 5)
                .addComponent(lblcita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblobservacion)
                .addGap(24, 24, 24)
                .addComponent(lblultimacita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblultimaobs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnhistarial)
                .addContainerGap())
        );

        jPanel1.setBounds(10, 10, 540, 190);
        p.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("Achivo");

        MenuCliente.setText("Centro Control Clientes");
        MenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuClienteActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCliente);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setText("Cerrar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Herramientas");

        jMenu4.setText("Mantenedores");

        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Vehículos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenu6.setText("Credito");

        jMenuItem4.setText("Financiamiento");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuItem7.setText("Ejecutivos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenu4.add(jMenu6);

        jMenu2.add(jMenu4);

        btnBuscaCliente.setText("Buscar Cliente");
        btnBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaClienteActionPerformed(evt);
            }
        });
        jMenu2.add(btnBuscaCliente);

        selCambiaClave.setText("Cambiar Contraseña");
        selCambiaClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selCambiaClaveActionPerformed(evt);
            }
        });
        jMenu2.add(selCambiaClave);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem1.setText("Acerca de...");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        MantenedorClientes mc=new MantenedorClientes();
        p.add(mc);
        mc.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        MantenedorFianaciamiento mf=new MantenedorFianaciamiento();
        p.add(mf);
        mf.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        MantenedorVehiculos mv=new MantenedorVehiculos();
        p.add(mv);
        mv.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClienteActionPerformed
        // TODO add your handling code here:
        ControlCliente newc=new ControlCliente();
        p.add(newc);
        newc.show();
    }//GEN-LAST:event_MenuClienteActionPerformed

    private void selCambiaClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selCambiaClaveActionPerformed
        // TODO add your handling code here:
        editarclave edc=new editarclave(usuario);
        p.add(edc);
        edc.show();
    }//GEN-LAST:event_selCambiaClaveActionPerformed

    private void btnhistarialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhistarialActionPerformed
        // TODO add your handling code here:
        HistorialNotificaciones hn=new HistorialNotificaciones();
        p.add(hn);
        hn.show();
    }//GEN-LAST:event_btnhistarialActionPerformed

    private void btnBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaClienteActionPerformed
        // TODO add your handling code here:
        BuscarCliente bc=new BuscarCliente();
        p.add(bc);
        bc.show();
    }//GEN-LAST:event_btnBuscaClienteActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        MantenedorEjecutivos me=new MantenedorEjecutivos();
        p.add(me);
        me.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                    new Escritorio().setVisible(true);
            }
        });
    }
    class RemindTask extends TimerTask  {
         public void run (){
             try {
                 BuscaCita();
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(Escritorio.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(Escritorio.class.getName()).log(Level.SEVERE, null, ex);
             }
          }  
      } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCliente;
    private javax.swing.JMenuItem btnBuscaCliente;
    private javax.swing.JButton btnhistarial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcita;
    private javax.swing.JLabel lblobservacion;
    private javax.swing.JLabel lbltiempo;
    private javax.swing.JLabel lblultimacita;
    private javax.swing.JLabel lblultimaobs;
    public javax.swing.JDesktopPane p;
    private javax.swing.JMenuItem selCambiaClave;
    // End of variables declaration//GEN-END:variables
}
