/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import com.cepardov.Utilidades.FuncionesSQL;
import com.cepardov.Utilidades.FuncionesSystem;
import com.cepardov.Utilidades.jcTrayIcon;
import java.awt.TrayIcon;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author cepardov
 */
public class Escritorio extends javax.swing.JFrame {
     jcTrayIcon jct = new jcTrayIcon( this );
     FuncionesSystem fs=new FuncionesSystem();
     FuncionesSQL data=new FuncionesSQL();
     Object[][] dtPrev;
     Timer timer;
     String fechaHoraAnterior=" ";
     String fechaHoraActual;
     String ultimaCita="";
     String ultimaObs="";
     
   /**
     * Creates new form Escritorio
     */
    public Escritorio() throws Exception {
        initComponents();
        setState(JFrame.MAXIMIZED_BOTH);
        this.mensajes();
        timer = new Timer(); 
        timer.schedule (new RemindTask(),0, 60000);
        fechaHoraAnterior=fs.fechahora();
        this.lbltiempo.setText(fs.fechahora());
        this.lblultimacita.setText("");
        this.lblultimaobservacion.setText("");
        this.lblobservacion.setText("");
    }

    public void mensajes(){
        jct.MensajeTrayIcon("Bienvenido (a)", TrayIcon.MessageType.INFO);
        jct.MensajeTrayIcon("Prototipo No estable", TrayIcon.MessageType.WARNING);
    }
    
    public void BuscaCita() throws ClassNotFoundException, SQLException{
        //Consulta y setea hora actual del sistema en variable local fechaHora desde clase funciones de sistema
        fechaHoraAnterior=fechaHoraActual;
        this.lbltiempo.setText(fechaHoraAnterior);
        fechaHoraActual=fs.fechahora();
        
        System.out.println("anterior="+fechaHoraAnterior);
        System.out.println("actual="+fechaHoraActual);
        //Busca nuevas citas
        Class.forName("com.mysql.jdbc.Driver");
        Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/BDSis", "root", "");
        Statement st = conexion.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM  `Cita` WHERE `fecha` BETWEEN  '"+fechaHoraAnterior+"' AND '"+fechaHoraActual+"'");
        while (rs.next()) {
            this.lblcita.setText("Usted Tiene una cita con"+" "+rs.getObject("nombre").toString()+" "+rs.getObject("fecha").toString());
            this.lblobservacion.setText("Observación: "+rs.getObject("observacion"));
            jct.MensajeTrayIcon(lblcita.getText(), TrayIcon.MessageType.INFO);
            System.out.println("result "+rs.getObject("idCita"));
            if(rs.getObject("idCita").toString().isEmpty()){
                jct.MensajeTrayIcon("No na", TrayIcon.MessageType.INFO);
            }
            }   
        rs.close();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lbltiempo = new javax.swing.JLabel();
        lblcita = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblobservacion = new javax.swing.JLabel();
        lblultimacita = new javax.swing.JLabel();
        lblultimaobservacion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cartera de Clientes - Javier Burgos - EB y Cia Ltada.");
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        p.setAutoscrolls(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Notificaciones Pendientes"));

        lbltiempo.setText("Hora");

        lblcita.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblcita.setText("No se encontraron nuevas notificaciones...");
        lblcita.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setText("Última Actualización: ");

        lblobservacion.setForeground(new java.awt.Color(255, 39, 0));
        lblobservacion.setText("Observacion");

        lblultimacita.setText("jLabel2");

        lblultimaobservacion.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblobservacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(lblultimacita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblultimaobservacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltiempo)
                    .addComponent(jLabel1))
                .addGap(5, 5, 5)
                .addComponent(lblcita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblobservacion)
                .addGap(18, 18, 18)
                .addComponent(lblultimacita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblultimaobservacion)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel1.setBounds(10, 10, 540, 190);
        p.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("Achivo");

        jMenu5.setText("Nuevo");

        jMenuItem7.setText("Cliente");
        jMenu5.add(jMenuItem7);

        jMenuItem6.setText("Cita");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenu1.add(jMenu5);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setText("Cerrar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Herramientas");

        jMenu4.setText("Mantenedores");

        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Vehículos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Financiamiento");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem1.setText("Acerca de...");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        MantenedorClientes mc=new MantenedorClientes();
        p.add(mc);
        mc.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        MantenedorFianaciamiento mf=new MantenedorFianaciamiento();
        p.add(mf);
        mf.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        MantenedorVehiculos mv=new MantenedorVehiculos();
        p.add(mv);
        mv.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        NuevaCita nc=new NuevaCita();
        p.add(nc);
        nc.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Escritorio().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Escritorio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    class RemindTask extends TimerTask  {
         public void run (){
             jct.MensajeTrayIcon("Comprobando notificaciones...", TrayIcon.MessageType.INFO);
             try {
                 BuscaCita();
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(Escritorio.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(Escritorio.class.getName()).log(Level.SEVERE, null, ex);
             }
          }  
      } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcita;
    private javax.swing.JLabel lblobservacion;
    private javax.swing.JLabel lbltiempo;
    private javax.swing.JLabel lblultimacita;
    private javax.swing.JLabel lblultimaobservacion;
    private javax.swing.JDesktopPane p;
    // End of variables declaration//GEN-END:variables
}
